"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""
import math

max_term = 4000000


def fibonacci_generator(max_term=math.inf):
    term_before_last, last_term, current_term = 0, 0, 1
    while current_term < max_term:
        yield current_term
        next_term = last_term + current_term
        term_before_last, last_term, current_term = last_term, current_term, next_term

print(sum(term for term in fibonacci_generator(max_term=max_term) if term % 2 == 0))